version: "3.8"

services:
  db:
    image: "mongo:4.0.27"
#    build: ./docker/mongodb
    restart: always
    tty: true
    ports:
      - "27019:27017"
    environment:
      - AUTH=yes
      - ADMIN_USER=admin
      - ADMIN_PASS=admin
      - APPLICATION_DATABASE=phantom
      - APPLICATION_DATABASE=phantom_admin
      - APPLICATION_PASS=IAG123456
    volumes:
      - ./logs/mongodb/:/var/log/mongodb/
      - ./docker/mongodb/db:/data/db