version: "3.8"

services:
  db:
    image: "mongo:4.0.27"
#    build: ./docker/mongodb
    restart: always
    tty: true
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=zjz_admin
      - MONGO_INITDB_ROOT_PASSWORD=qs123456..
      - MONGO_INITDB_DATABASE=zjz
    volumes:
      - ./docker/mongodb/db:/data/db
      - ./docker/mongodb/log:/data/logs
      - ./docker/mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
